# Generated by Django 2.0 on 2019-02-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190215_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friend_request',
            new_name='status',
        ),
    ]
