# Generated by Django 2.0 on 2019-02-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190218_1621'),
        ('accounts', '0006_auto_20190218_1441'),
    ]

    operations = [
    ]
