# Generated by Django 2.0 on 2019-02-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190218_1441'),
        ('accounts', '0006_auto_20190220_1309'),
    ]

    operations = [
    ]
