# Generated by Django 2.0 on 2019-02-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_langage',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
