# Generated by Django 2.0 on 2019-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190205_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='original_langage',
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
